name:                regreg
version:             0.1.0.0
github:              "githubuser/regreg"
license:             BSD3
author:              "Able Arthy"
maintainer:          "ablearthy@gmail.com"
copyright:           "2023 Able Arthy"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ablearthy/regreg#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- unordered-containers
- vector
- text
- containers
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2021

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost

library:
  source-dirs: src

executables:
  regreg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regreg

tests:
  regreg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regreg
    - hspec
    - hspec-contrib
